Fast-Food-Du-An-master/Fast-Food/Controllers/HoaDonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fast_Food.Models;

namespace Fast_Food.Controllers
{
    public class HoaDonsController : Controller
    {
        private readonly DoAnStoreContext _context;

        public HoaDonsController(DoAnStoreContext context)
        {
            _context = context;
        }
       

        [HttpPost]
        public IActionResult ThanhToan(int id)
        {
            var hoaDon = _context.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return NotFound();
            }

            // Cập nhật trạng thái đơn hàng thành "Đã thanh toán"
            hoaDon.TrangThaiThanhToan = "Đã thanh toán";
            _context.Update(hoaDon);
            _context.SaveChanges();

            TempData["SuccessMessage"] = "Đơn hàng đã được thanh toán thành công!";

            // Chuyển hướng đến trang danh sách hóa đơn
            return RedirectToAction("Index");
        }
        // GET: HoaDons
        public async Task<IActionResult> Index()
        {
            var maKhachHang = HttpContext.Session.GetString("MaKhachHang");
            var maNhanVien = HttpContext.Session.GetString("MaNhanVien");
            if (string.IsNullOrEmpty(maKhachHang))
            {
                return RedirectToAction("Login", "DangNhap"); // Nếu chưa đăng nhập, chuyển hướng đến trang đăng nhập
            }

            int maKH = int.Parse(maKhachHang); // Chuyển đổi mã khách hàng từ string sang int

            var hoaDons = await _context.HoaDons
                .Where(h => h.MaKhachHang == maKH) // Lọc theo mã khách hàng
                .Include(h => h.MaKhachHangNavigation)
                .Include(h => h.MaNhanVienNavigation)
                .Include(h => h.MaVoucherNavigation)
                .ToListAsync();

            return View(hoaDons);
        }
        public IActionResult CancelOrder(int id)
        {
            var hoaDon = _context.HoaDons
                .Include(h => h.ChiTietHoaDons)
                .FirstOrDefault(h => h.MaHoaDon == id);

            if (hoaDon == null || hoaDon.TrangThaiDonHang == "Đã hủy")
            {
                return NotFound();
            }

            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    // Cập nhật trạng thái hóa đơn
                    hoaDon.TrangThaiDonHang = "Đã hủy";
                    hoaDon.TrangThaiThanhToan = "Đã hủy";
                    hoaDon.ThoiGianKetThuc = DateTime.Now;
                    // Hoàn lại số lượng món ăn
                    foreach (var chiTiet in hoaDon.ChiTietHoaDons)
                    {
                        var monAn = _context.MonAns.Find(chiTiet.MaMon);
                        if (monAn != null)
                        {
                            monAn.SoLuong += chiTiet.SoLuong.Value;
                            monAn.TrangThai = true; // Món ăn có hàng trở lại
                        }
                    }

                    _context.SaveChanges();
                    transaction.Commit();
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> HoaDon(string status)
        {
            // Kiểm tra session người dùng đã đăng nhập hay chưa
            var maKhachHang = HttpContext.Session.GetString("MaKhachHang");
            var maNhanVien = HttpContext.Session.GetString("MaNhanVien");

            // Nếu chưa đăng nhập, chuyển hướng về trang Login
            if (string.IsNullOrEmpty(maKhachHang) && string.IsNullOrEmpty(maNhanVien))
            {
                return RedirectToAction("Login", "DangNhap");
            }

            var hoaDons = _context.HoaDons
                .Include(h => h.MaKhachHangNavigation)
                .Include(h => h.MaNhanVienNavigation)
                .Include(h => h.MaVoucherNavigation)
                .AsQueryable();

            if (!string.IsNullOrEmpty(status))
            {
                switch (status)
                {
                    case "Canceled":
                        hoaDons = hoaDons.Where(h => h.TrangThaiDonHang == "Đã hủy");
                        break;
                    case "Preparing":
                        hoaDons = hoaDons.Where(h => h.TrangThaiDonHang == "Đang chuẩn bị");
                        break;
                    case "Shipping":
                        hoaDons = hoaDons.Where(h => h.TrangThaiDonHang == "Đang giao hàng");
                        break;
                    case "DaThanhToan":
                        hoaDons = hoaDons.Where(h => h.TrangThaiDonHang == "Đã thanh toán");
                        break;
                    case "HoanThanh":
                        hoaDons = hoaDons.Where(h => h.TrangThaiDonHang == "Hoàn thành");
                        break;
                    default:
                        break;
                }
            }

            var hoaDonsList = await hoaDons.ToListAsync();
            return View(hoaDonsList);
        }


        // GET: Hiển thị form chỉnh sửa trạng thái đơn hàng
        [HttpPost]
        public async Task<IActionResult> CapNhatTrangThai(int id)
        {
            var hoaDon = await _context.HoaDons.FindAsync(id);
            if (hoaDon == null)
            {
                TempData["ErrorMessage"] = "Không tìm thấy hóa đơn!";
                return RedirectToAction("HoaDon");
            }

            string trangThaiHienTai = hoaDon.TrangThaiDonHang.Trim().ToLower();

            switch (trangThaiHienTai)
            {
                case "đang chuẩn bị":
                    hoaDon.TrangThaiDonHang = "Đang giao hàng";
                    hoaDon.TrangThaiThanhToan = "Đang xử lý";
                    break;
                case "đang giao hàng":
                    hoaDon.TrangThaiDonHang = "Đã thanh toán";
                    hoaDon.TrangThaiThanhToan = "Đã thanh toán";
                    break;
                case "đã thanh toán":
                    hoaDon.TrangThaiDonHang = "Hoàn thành";
                    hoaDon.TrangThaiThanhToan = "Đã thanh toán";
                    hoaDon.ThoiGianKetThuc = DateTime.Now;
                    break;
                case "hoàn thành":
                    TempData["ErrorMessage"] = "Đơn hàng đã hoàn thành, không thể cập nhật tiếp!";
                    return RedirectToAction("HoaDon");
                default:
                    TempData["ErrorMessage"] = "Trạng thái đơn hàng không hợp lệ!";
                    return RedirectToAction("HoaDon");
            }

            _context.HoaDons.Update(hoaDon);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Cập nhật trạng thái đơn hàng thành công!";
            return RedirectToAction("HoaDon");
        }


        // GET: HoaDons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons
                .Include(h => h.MaKhachHangNavigation)
                .Include(h => h.MaNhanVienNavigation)
                .Include(h => h.MaVoucherNavigation)
                .Include(h => h.ChiTietHoaDons) // Lấy chi tiết hóa đơn
                    .ThenInclude(ct => ct.MaMonNavigation) // Lấy thông tin món ăn
                .FirstOrDefaultAsync(m => m.MaHoaDon == id);

            if (hoaDon == null)
            {
                return NotFound();
            }

            return View(hoaDon);
        }
        // GET: HoaDons/Create
        public IActionResult Create()
        {
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "MaKhachHang");
            ViewData["MaNhanVien"] = new SelectList(_context.NhanViens, "MaNhanVien", "MaNhanVien");
            ViewData["MaVoucher"] = new SelectList(_context.Vouchers, "MaVoucher", "MaVoucher");
            return View();
        }

        // POST: HoaDons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHoaDon,MaKhachHang,MaNhanVien,ThoiGianDat,ThoiGianKetThuc,TrangThaiDonHang,TrangThaiThanhToan,SdtlienHe,DiaChiGiaoHang,DanhGia,MaVoucher")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hoaDon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "MaKhachHang", hoaDon.MaKhachHang);
            ViewData["MaNhanVien"] = new SelectList(_context.NhanViens, "MaNhanVien", "MaNhanVien", hoaDon.MaNhanVien);
            ViewData["MaVoucher"] = new SelectList(_context.Vouchers, "MaVoucher", "MaVoucher", hoaDon.MaVoucher);
            return View(hoaDon);
        }

        // GET: HoaDons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoaDon = await _context.HoaDons.FindAsync(id);
            if (hoaDon == null)
            {
                return NotFound();
            }
            ViewData["MaKhachHang"] = new SelectList(_context.KhachHangs, "MaKhachHang", "MaKhachHang", hoaDon.MaKhachHang);
            ViewData["MaNhanVien"] = new SelectList(_context.NhanViens, "MaNhanVien", "MaNhanVien", hoaDon.MaNhanVien);

Fast-Food-Du-An-master/Fast-Food/Controllers/MomoController.cs
using Fast_Food.Momo;
using Microsoft.AspNetCore.Mvc;

namespace Fast_Food.Controllers
{
    public class MomoController : Controller
    {
        private IMomoService _momoService;
        //private readonly IVnPayService _vnPayService;
        public MomoController(IMomoService momoService)
        {
            _momoService = momoService;
        }
        //[HttpPost]
        //[Route("CreatePaymentUrl")]
        //public async Task<IActionResult> CreatePaymentUrl(OrderInfoModel model)
        //{
        //    var response = await _momoService.CreatePaymentAsync(model);
        //    return Redirect(response.PayUrl);
        //}
        [Route("Momo/CreatePaymentUrl")]
        public async Task<IActionResult> CreatePaymentUrl([FromServices] IMomoService momoService)
        {
            var order = new OrderInfoModel
            {
                FullName = "Nguyễn Văn A",
                Amount = 100000,
                OrderInfo = "Thanh toán đơn hàng"
            };

            var response = await momoService.CreatePaymentAsync(order);
            return Redirect(response.PayUrl);
        }

        [HttpGet]
        public IActionResult Pa()
        {
            var re = _momoService.PaymentExecuteAsync(HttpContext.Request.Query);
            return View(re);
        }
    }
}

Fast-Food-Du-An-master/Fast-Food/Views/HoaDons/Index.cshtml
@model IEnumerable<Fast_Food.Models.HoaDon>

@{
    ViewData["Title"] = "Danh sách Hóa Đơn";
}

<h2 class="mb-4 text-center">Danh sách Hóa Đơn</h2>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success text-center">
        @TempData["SuccessMessage"]
    </div>
}

<table class="table table-bordered table-striped text-center align-middle">
    <thead class="table-dark">
        <tr>
            <th>STT</th>
            <th>Món Ăn Đặt</th>
            <th>Thời Gian Đặt</th>
            <th>Thời Gian Kết Thúc</th>
            <th>Trạng Thái Đơn Hàng</th>
            <th>Trạng Thái Thanh Toán</th>
            <th>Số Điện Thoại</th>
            <th>Địa Chỉ Giao Hàng</th>
            <th>Tổng Tiền</th>
            <th>Thao Tác</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Select((value, idx) => new { value, idx }))
        {
            <tr>
                <td>@(item.idx + 1)</td> <!-- Số thứ tự -->
                <td>
                    <a asp-action="Details" asp-route-id="@item.value.MaHoaDon" class="btn btn-info btn-sm">
                        📜 Xem Chi Tiết
                    </a>
                </td>
                <td>@Html.DisplayFor(modelItem => item.value.ThoiGianDat)</td>
                <td>@Html.DisplayFor(modelItem => item.value.ThoiGianKetThuc)</td>
                <td>
                    <span class="badge @(item.value.TrangThaiDonHang == "Đã hủy" ? "bg-danger" :
                                        item.value.TrangThaiDonHang == "Hoàn thành" ? "bg-success" : "bg-warning text-dark")">
                        @Html.DisplayFor(modelItem => item.value.TrangThaiDonHang)
                    </span>
                </td>
                <td>
                    <span class="badge @(item.value.TrangThaiThanhToan == "Đã thanh toán" ? "bg-success" : "bg-secondary")">
                        @Html.DisplayFor(modelItem => item.value.TrangThaiThanhToan)
                    </span>
                </td>
                <td>@Html.DisplayFor(modelItem => item.value.SdtlienHe)</td>
                <td>@Html.DisplayFor(modelItem => item.value.DiaChiGiaoHang)</td>
                <td><strong>@($"{(item.value.TongTien):N0}")₫</strong></td>
                <td>
                    @if (item.value.TrangThaiDonHang == "Chờ xác nhận" || item.value.TrangThaiDonHang == "Đang xử lý")
                    {
                        <form asp-action="CancelOrder" asp-controller="HoaDons" method="post" class="d-inline">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@item.value.MaHoaDon" />
                            <button type="submit" class="btn btn-danger btn-sm"
                                    onclick="return confirm('Bạn có chắc muốn hủy đơn hàng này không?');">
                                🛑 Hủy Đơn
                            </button>
                        </form>
                    }

                    @if (item.value.TrangThaiThanhToan == "Chưa thanh toán")
                    {
                        <form method="post" asp-action="CreatePaymentUrl" asp-controller="Momo">
                            <input type="hidden" name="OrderId" value="@Guid.NewGuid().ToString()" />
                            <input type="hidden" name="FullName" value="@item.value.MaKhachHang" />
                            <input type="hidden" name="Amount" value="@item.value.TongTien" />
                            <input type="hidden" name="OrderInfo" value="Thanh toán đơn hàng #@item.value.MaHoaDon qua MoMo tại Fast_Food" />

                            <button class="btn btn-danger btn-sm" type="submit">💰 Thanh toán MoMo</button>
                        </form>
                    }
                    else
                    {
                        <button class="btn btn-secondary btn-sm" disabled>Không thể thanh toán</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>